spring.application.name=smartshift-backend

jwt.access.secret=zEW1GWOVrp9tUTaJU9R5HyzFb9T2ARyU7mTpaCIOs+4=
jwt.access.expiration=900000

jwt.refresh.secret=xYABBkkSpdu2embrDOYE5X/1vZm51koPM5HZ3E+i7Vc
jwt.refresh.expiration=604800000


spring.datasource.url=jdbc:postgresql://localhost:5433/SmartShift
spring.datasource.username=postgres
spring.datasource.password=Skm@6705

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379