-- Review before applying. Existing users require an organization-specific role backfill.

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    billing_provider_customer_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES account(id),
    provider_subscription_id VARCHAR(255) NOT NULL,
    provider_transaction_id VARCHAR(255) NOT NULL UNIQUE,
    amount NUMERIC(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL,
    message VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_transaction_status CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING'))
);

CREATE TABLE organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES account(id) ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    subscription_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'TRIAL',
    emergency_selection_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_organization_account_name UNIQUE (account_id, name),
    CONSTRAINT ck_organization_status CHECK (status IN ('TRIAL', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELLED')),
    CONSTRAINT ck_emergency_selection_type CHECK (emergency_selection_type IN ('FIFO', 'SKILL_MATCHER', 'MANAGER_CHOICE', 'HYBRID'))
);

CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organization(id),
    transaction_id BIGINT NOT NULL REFERENCES transactions(id),
    subscription_type VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE organization
    ADD CONSTRAINT fk_organization_subscription
    FOREIGN KEY (subscription_id) REFERENCES subscription(id);

CREATE TABLE organization_settings (
    organization_id BIGINT PRIMARY KEY REFERENCES organization(id) ON DELETE CASCADE,
    proximity_weight NUMERIC(19, 6),
    skill_match_weight NUMERIC(19, 6),
    overtime_risk_weight NUMERIC(19, 6),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE user_organization_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    organization_id BIGINT NOT NULL REFERENCES organization(id),
    role VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_membership_user_organization UNIQUE (user_id, organization_id),
    CONSTRAINT ck_membership_role CHECK (role IN ('ADMIN', 'MANAGER', 'EMPLOYEE'))
);

-- Migration step 1: add the account scope without making existing rows invalid.
ALTER TABLE users ADD COLUMN account_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_account FOREIGN KEY (account_id) REFERENCES account(id);

-- Migration step 2: create user_organization_membership (above).
-- Migration step 3: backfill account_id and memberships from an approved data mapping.
-- The old schema has no organization_id on users, so an automatic role backfill
-- is not deterministic. Populate this mapping before applying the next statements.
-- Example review-only shape:
-- INSERT INTO user_organization_membership (user_id, organization_id, role, created_at)
-- SELECT u.id, m.organization_id, u.role, CURRENT_TIMESTAMP
-- FROM users u JOIN approved_user_organization_map m ON m.user_id = u.id;

-- Migration step 4: after confirming the backfill, enforce account_id and remove role.
-- ALTER TABLE users ALTER COLUMN account_id SET NOT NULL;
-- ALTER TABLE users DROP COLUMN role;